'use client'

/**
 * ExecutiveSummary — DAF Virtuel typing animation component
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *
 * Displays the 3-sentence executive summary generated by SCORIS
 * with a typewriter animation that mimics a virtual CFO dictating.
 *
 * Features:
 *   - Character-by-character reveal with variable speed
 *   - Blinking cursor during typing
 *   - Subtle fade-in on mount
 *   - Optional TRESORIS badge when enrichment data is present
 *
 * Used in:
 *   - Wizard synthesis phase (top of synthesis section)
 *   - mon-diagnostic (future)
 */

import { useState, useEffect, useRef } from 'react'
import { Sparkles } from 'lucide-react'

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TYPING CONFIG
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/** Base typing speed (ms per character) */
const BASE_SPEED = 18
/** Pause after sentence-ending punctuation (ms) */
const SENTENCE_PAUSE = 280
/** Pause after comma/semicolon (ms) */
const CLAUSE_PAUSE = 80
/** Characters that trigger a sentence pause */
const SENTENCE_ENDERS = new Set(['.', '!', '?'])
/** Characters that trigger a clause pause */
const CLAUSE_ENDERS = new Set([',', ';', ':', '—', '–'])

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMPONENT
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

interface ExecutiveSummaryProps {
  /** The full executive summary text from ScorisOutput */
  text: string
  /** Whether TRESORIS enrichment contributed to this summary */
  enrichedByTresoris?: boolean
  /** CSS class name */
  className?: string
}

export function ExecutiveSummary({
  text,
  enrichedByTresoris = false,
  className = '',
}: ExecutiveSummaryProps) {
  const [displayedLength, setDisplayedLength] = useState(0)
  const [isComplete, setIsComplete] = useState(false)
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!text) return

    // Reset on text change
    setDisplayedLength(0)
    setIsComplete(false)

    let currentIndex = 0

    function typeNext() {
      if (currentIndex >= text.length) {
        setIsComplete(true)
        return
      }

      currentIndex++
      setDisplayedLength(currentIndex)

      // Determine delay for next character
      const char = text[currentIndex - 1]
      let delay = BASE_SPEED

      // Add natural pauses at punctuation
      if (SENTENCE_ENDERS.has(char) && currentIndex < text.length && text[currentIndex] === ' ') {
        delay = SENTENCE_PAUSE
      } else if (CLAUSE_ENDERS.has(char)) {
        delay = CLAUSE_PAUSE
      }

      // Slight random variation for natural feel
      delay += Math.random() * 8 - 4

      timeoutRef.current = setTimeout(typeNext, delay)
    }

    // Start after a brief delay (let the component mount gracefully)
    timeoutRef.current = setTimeout(typeNext, 400)

    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current)
      }
    }
  }, [text])

  if (!text) return null

  const displayedText = text.slice(0, displayedLength)

  return (
    <div
      ref={containerRef}
      className={`relative px-5 py-5 bg-white/[0.03] border border-white/10 rounded-lg ${className}`}
    >
      {/* Header badge */}
      <div className="flex items-center gap-2 mb-3">
        <Sparkles className="w-3.5 h-3.5 text-amber-400" />
        <span className="text-[10px] font-semibold text-gray-500 uppercase tracking-[0.15em]">
          Synthèse DAF Virtuel
        </span>
        {enrichedByTresoris && (
          <span className="inline-flex items-center gap-1 px-1.5 py-0.5 text-[9px] font-medium bg-purple-500/10 text-purple-400 border border-purple-500/20 rounded-full">
            TRESORIS
          </span>
        )}
      </div>

      {/* Typing text */}
      <p className="text-sm text-gray-300 leading-relaxed min-h-[3.5rem]">
        {displayedText}
        {/* Blinking cursor */}
        {!isComplete && (
          <span className="inline-block w-[2px] h-4 bg-amber-400/80 ml-0.5 align-text-bottom animate-pulse" />
        )}
      </p>

      {/* Subtle fade gradient at bottom when still typing */}
      {!isComplete && displayedLength > 0 && (
        <div className="absolute bottom-0 left-0 right-0 h-6 bg-gradient-to-t from-slate-950/20 to-transparent rounded-b-lg pointer-events-none" />
      )}
    </div>
  )
}
