import type { BlogArticleRegistryEntry } from './articlesRegistry'

/** Données catalogue — source unique pour index, SEO et sitemap. */
export const BLOG_REGISTRY_ENTRIES: BlogArticleRegistryEntry[] = [
    {
        slug: 'dso-dpo-dio-trois-indicateurs-tresorerie',
        title: 'DSO, DPO et DIO : les 3 indicateurs de trésorerie à maîtriser',
        description: 'Trois acronymes, trois fenêtres sur la même réalité : comment l\'argent circule dans votre entreprise. Séparément, chacun raconte une partie de l\'histoire. Ensemble, ils racontent tout.',
        displayDate: '16 mai 2026',
        publishedAt: '2026-05-16',
        readTime: '7 min',
        category: 'Note Stratégique',
        tags: ['DSO', 'DPO', 'DIO', 'Trésorerie', 'BFR', 'Cash Conversion Cycle'],
        keywords: ['dso', 'dpo', 'dio', 'cash conversion cycle', 'bfr', 'trésorerie pme', 'indicateurs trésorerie'],
        featured: true,
        image: '/images/cash-flow-prev.png',
        type: 'strategique'
    },
    {
        slug: 'ebitda-vs-resultat-net-banquier',
        title: 'EBITDA vs résultat net : pourquoi votre banquier s\'en fiche d\'un et pas de l\'autre',
        description: 'Votre expert-comptable vous montre un résultat net positif. Votre banquier, lui, regarde autre chose. Ce décalage coûte des refus de crédit et des négociations ratées.',
        displayDate: '16 mai 2026',
        publishedAt: '2026-05-16',
        readTime: '5 min',
        category: 'Note Stratégique',
        tags: ['EBITDA', 'Résultat net', 'Banque', 'Financement', 'PME'],
        keywords: ['ebitda', 'résultat net', 'dette nette ebitda', 'financement pme', 'ratio bancaire', 'banquier pme'],
        featured: true,
        image: '/images/bureau-nuit.png',
        type: 'strategique'
    },
    {
        slug: 'pge-dso-double-pression-tresorerie-2026',
        title: 'Remboursement PGE + DSO qui s\'allonge : le double étau de trésorerie des PME en 2026',
        description: 'Deux pressions distinctes s\'exercent simultanément sur la trésorerie des PME françaises. L\'une vient de l\'intérieur - les PGE arrivent à échéance. L\'autre vient de l\'extérieur - les clients paient de plus en plus tard.',
        displayDate: '10 mai 2026',
        publishedAt: '2026-05-10',
        readTime: '8 min',
        category: 'Note Stratégique',
        tags: ['PGE', 'DSO', 'Trésorerie', 'PME', 'Cash'],
        keywords: ['pge', 'dso', 'trésorerie', 'pme', 'cash'],
        featured: true,
        image: '/images/cash-flow-prev.png',
        type: 'strategique'
    },
    {
        slug: 'ia-finance-entreprise-grands-groupes-industrialisent-pme-experimentent-2026',
        title: 'L\'IA en Finance d\'entreprise : les grands groupes industrialisent, les PME expérimentent. Et toi, tu en es où ?',
        description: 'Seulement 10% des cas d\'usage financiers sont réellement déployés en France. Ce que font les grands groupes que les PME ne font pas encore — et les 3 cas d\'usage accessibles dès maintenant.',
        displayDate: '13 mai 2026',
        publishedAt: '2026-05-13',
        readTime: '6 min',
        category: 'Intelligence Artificielle',
        tags: ['IA Finance', 'PME', 'Transformation digitale', 'KPMG', 'ROI'],
        keywords: ['ia finance', 'pme', 'transformation digitale', 'kpmg', 'roi'],
        featured: true,
        image: '/images/bureau-nuit.png',
        type: 'strategique'
    },
    {
        slug: 'facturation-electronique-2026-ce-que-tu-dois-vraiment-faire-avant-septembre',
        title: 'Facturation électronique 2026 : ce que tu dois vraiment faire avant septembre',
        description: 'À 4 mois de l\'échéance, 65% des dirigeants de TPE ne connaissent pas le contenu exact de la réforme. Calendrier, formats, sanctions et checklist actionnable en 3 étapes.',
        displayDate: '12 mai 2026',
        publishedAt: '2026-05-12',
        readTime: '6 min',
        category: 'Réglementation',
        tags: ['Facturation électronique', 'Factur-X', 'DGFiP', 'Conformité', 'TVA'],
        keywords: ['facturation électronique 2026', 'e-facture obligatoire', 'factur-x', 'pdp dgfip', 'réforme facture tva', 'chorus pro'],
        featured: true,
        image: '/images/bureau-nuit.png',
        type: 'operationnel'
    },
    {
        slug: 'dso-superieur-mediane-sectorielle-modele',
        title: 'DSO supérieur à la médiane sectorielle : que révèle vraiment votre modèle ?',
        description: 'Un DSO élevé n\'est pas qu\'un problème de recouvrement. C\'est souvent le symptôme d\'un déséquilibre structurel entre modèle commercial et organisation financière.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '11 min',
        category: 'Note Stratégique',
        tags: ['DSO', 'Analyse structurelle', 'Modèle économique', 'DAF'],
        keywords: ['dso', 'délai paiement clients', 'trésorerie', 'modèle commercial', 'cash management'],
        image: '/images/bureau-nuit.png',
        type: 'strategique'
    },
    {
        slug: 'bfr-structurellement-eleve-commercial-organisationnel',
        title: 'BFR structurellement élevé : problème commercial ou problème organisationnel ?',
        description: 'Quand le BFR dépasse durablement les normes sectorielles, la cause est rarement unique. Lecture croisée des facteurs commerciaux, opérationnels et financiers.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '13 min',
        category: 'Note Stratégique',
        tags: ['BFR', 'Analyse structurelle', 'Organisation', 'DAF'],
        keywords: ['bfr', 'besoin fonds roulement', 'trésorerie pme', 'cycle exploitation', 'cash'],
        image: '/images/bfr.png',
        type: 'strategique'
    },
    {
        slug: 'pme-sous-estiment-fragilite-cash',
        title: 'Pourquoi 70 % des PME sous-estiment leur fragilité cash',
        description: 'La rentabilité masque souvent une vulnérabilité de trésorerie. Analyse des mécanismes qui conduisent les PME rentables à une impasse de liquidité.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '10 min',
        category: 'Note Stratégique',
        tags: ['Cash', 'Fragilité', 'PME', 'Trésorerie', 'DAF'],
        keywords: ['trésorerie pme', 'fragilité cash', 'liquidité', 'pilotage financier'],
        image: '/images/cash-flow-prev.png',
        type: 'strategique'
    },
    {
        slug: 'marge-correcte-cash-fragile-piege-croissance',
        title: 'Marge correcte, cash fragile : le piège classique des PME en croissance',
        description: 'Une marge brute confortable ne protège pas de la rupture de trésorerie. Pourquoi la croissance est le moment le plus dangereux pour le cash.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '12 min',
        category: 'Note Stratégique',
        tags: ['Marge', 'Cash', 'Croissance', 'PME', 'DAF'],
        keywords: ['marge brute', 'trésorerie', 'pme croissance', 'cash flow', 'bfr'],
        image: '/images/marge.png',
        type: 'strategique'
    },
    {
        slug: 'daf-externalise-vs-expert-comptable-confusion',
        title: 'DAF externalisé vs expert-comptable : rôles et confusion dangereuse',
        description: 'L\'expert-comptable produit les comptes. Le DAF les interprète et arbitre. Confondre les deux expose l\'entreprise à des décisions prises sans lecture financière.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '9 min',
        category: 'Note Stratégique',
        tags: ['DAF externalisé', 'Expert-comptable', 'Positionnement', 'Direction financière'],
        keywords: ['daf externalisé', 'expert comptable', 'direction financière', 'pilotage pme'],
        image: '/images/bureau.png',
        type: 'strategique'
    },
    {
        slug: 'a-partir-quel-ca-faut-il-un-daf',
        title: 'À partir de quel chiffre d\'affaires faut-il un DAF ?',
        description: 'Le seuil de complexité financière ne dépend pas que du CA. Nombre de clients, saisonnalité, BFR structurel : les vrais critères de déclenchement.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '10 min',
        category: 'Note Stratégique',
        tags: ['DAF', 'Seuil CA', 'Direction financière', 'PME'],
        keywords: ['daf externalisé', 'daf pme', 'direction financière externalisée', 'quand recruter daf'],
        image: '/images/moi-bureau.png',
        type: 'strategique'
    },
    {
        slug: '4-priorites-daf-90-jours',
        title: 'Les 4 priorités d\'un DAF sur 90 jours',
        description: 'Trésorerie, marge, structure, reporting : la séquence d\'intervention d\'un DAF qui prend un mandat. Ce qui se joue dans les 3 premiers mois.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '11 min',
        category: 'Note Stratégique',
        tags: ['DAF', 'Priorités', '90 jours', 'Méthodologie', 'PME'],
        keywords: ['daf externalisé', 'direction financière', 'pilotage financier', '90 jours'],
        image: '/images/vue-NY.png',
        type: 'strategique'
    },
    {
        slug: 'pilotage-financier-change-pme-5-20m',
        title: 'Ce qu\'un vrai pilotage financier change dans une PME 5–20M\\u20ac',
        description: 'Avant/après : les transformations concrètes quand une PME passe d\'une comptabilité subie à un pilotage financier structuré.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '14 min',
        category: 'Note Stratégique',
        tags: ['Pilotage financier', 'PME', 'Transformation', 'DAF', 'Direction financière'],
        keywords: ['pilotage financier', 'pme', 'tableaux de bord', 'daf', 'reporting financier'],
        image: '/images/bureau-nuit.png',
        type: 'strategique'
    },
    {
        slug: 'pme-b2b-6m-240k-cash-libere-4-mois',
        title: 'Comment une PME B2B à 6M€ a libéré 240k€ de cash en 4 mois',
        description: 'DSO de 72 jours, BFR en dérive, trésorerie sous tension. Diagnostic structuré, plan d\'action en 3 phases, résultat chiffré : +240k€ de cash disponible.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '11 min',
        category: 'Étude de cas',
        tags: ['Cash', 'DSO', 'BFR', 'PME B2B', 'Résultats'],
        keywords: ['étude de cas', 'trésorerie pme', 'dso', 'cash libéré', 'daf externalisé'],
        image: '/images/bureau.png',
        type: 'strategique'
    },
    {
        slug: 'reduire-dso-62-41-jours-relation-client',
        title: 'Comment réduire un DSO de 62 à 41 jours sans détériorer la relation client',
        description: 'PME de services à 4,5M€ de CA. DSO chroniquement élevé. 3 leviers activés en 90 jours : segmentation client, process facturation, relance structurée.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '10 min',
        category: 'Étude de cas',
        tags: ['DSO', 'Recouvrement', 'Relation client', 'PME Services'],
        keywords: ['réduire dso', 'relation client', 'pme b2b', 'cash management', 'recouvrement'],
        image: '/images/vue-NY.png',
        type: 'strategique'
    },
    {
        slug: 'pme-8m-risque-dependance-sous-estime',
        title: 'Pourquoi cette PME à 8M€ de CA sous-estimait son risque de dépendance',
        description: 'Un client représente 38% du CA. Marge confortable, dirigeant serein. Analyse structurelle : le risque était systémique et invisible dans les tableaux de bord.',
        displayDate: '21 février 2026',
        publishedAt: '2026-02-21',
        readTime: '12 min',
        category: 'Étude de cas',
        tags: ['Concentration client', 'Risque', 'PME', 'Diversification'],
        keywords: ['risque dépendance client', 'concentration client', 'pme', 'diagnostic financier', 'daf'],
        image: '/images/marge.png',
        type: 'strategique'
    },
    {
        slug: 'dashboard-financier-mort-agents-ia-2026',
        title: 'Pourquoi votre Dashboard Financier est mort (et ce qui le remplace en 2026)',
        description: 'Le Dashboard affiche le passé. Les Agents IA prédisent l\'avenir. Découvrez DASHIS, TRESORIS, MARGIS et SCENARIS : la révolution du pilotage automatique 24/7',
        displayDate: '9 février 2026',
        publishedAt: '2026-02-09',
        readTime: '8 min',
        category: 'Intelligence Artificielle',
        tags: ['Agents IA', 'Automation', 'Trésorerie', 'Pilotage', 'Dashboard'],
        keywords: ['agents ia', 'automation', 'trésorerie', 'pilotage', 'dashboard'],
        featured: true,
        image: '/images/ai-oversight-control.png'
    },
    {
        slug: 'lire-bilan-compte-resultat-guide-pratique',
        title: 'Lire un bilan et un compte de résultat : guide pratique',
        description: 'Apprenez à décrypter vos états financiers en 15 minutes : bilan, compte de résultat, signaux d\'alerte et questions à poser à votre comptable',
        displayDate: '25 janvier 2026',
        publishedAt: '2026-01-25',
        readTime: '12 min',
        category: 'Gestion',
        tags: ['Bilan', 'Compte de résultat', 'États financiers', 'Comptabilité'],
        keywords: ['bilan comptable', 'compte de résultat', 'états financiers', 'lecture bilan', 'comptabilité pme'],
        image: '/images/bureau-nuit.png'
    },
    {
        slug: 'eva-roic-illusion-performance',
        title: 'Pourquoi une entreprise rentable peut détruire de la valeur',
        description: 'EVA, ROIC et WACC : découvrez pourquoi la rentabilité comptable ne suffit pas et comment mesurer la création de valeur réelle',
        displayDate: '25 janvier 2026',
        publishedAt: '2026-01-25',
        readTime: '14 min',
        category: 'Analyse',
        tags: ['EVA', 'ROIC', 'WACC', 'Valeur', 'Performance'],
        keywords: ['eva', 'roic', 'wacc', 'création de valeur', 'rentabilité économique', 'performance financière'],
        image: '/images/bureau.png'
    },
    {
        slug: '5-erreurs-tresorerie-pme',
        title: '5 erreurs de trésorerie qui coûtent cher aux PME',
        description: 'Les erreurs fatales que commettent 80% des dirigeants de PME avec leur trésorerie, et comment les éviter',
        displayDate: '18 décembre 2025',
        publishedAt: '2025-12-18',
        readTime: '7 min',
        category: 'Trésorerie',
        tags: ['Trésorerie', 'PME', 'Erreurs', 'Cash', 'Pilotage'],
        keywords: ['trésorerie', 'pme', 'erreurs', 'cash', 'pilotage'],
        image: '/images/bureau-nuit.png'
    },
    {
        slug: 'calcul-dso-formule-2025',
        title: 'Comment calculer son DSO (formule PCG 2025)',
        description: 'Guide complet pour calculer le DSO avec exemples pratiques et benchmarks sectoriels français',
        displayDate: '16 décembre 2025',
        publishedAt: '2025-11-28',
        readTime: '8 min',
        category: 'KPIs',
        tags: ['DSO', 'Trésorerie', 'Formule', 'PCG 2025'],
        keywords: ['dso', 'délai paiement', 'créances clients', 'pcg 2025', 'kpi financier'],
        image: '/images/vue-NY.png'
    },
    {
        slug: '5-kpis-financiers-pme',
        title: 'Les 5 KPIs financiers essentiels pour PME',
        description: 'Découvrez les indicateurs clés que tout dirigeant de PME devrait suivre mensuellement',
        displayDate: '18 décembre 2025',
        publishedAt: '2025-11-28',
        readTime: '6 min',
        category: 'Gestion',
        tags: ['KPIs', 'PME', 'Indicateurs', 'Pilotage'],
        keywords: ['kpi financier', 'pme', 'indicateurs', 'pilotage', 'gestion financière'],
        image: '/images/bureau.png'
    },
    {
        slug: 'bfr-formule-optimisation',
        title: 'BFR : formule de calcul et optimisation 2025',
        description: 'Tout savoir sur le Besoin en Fonds de Roulement : calcul, interprétation et leviers d\'optimisation',
        displayDate: '17 décembre 2025',
        publishedAt: '2025-11-28',
        readTime: '10 min',
        category: 'Trésorerie',
        tags: ['BFR', 'Trésorerie', 'Optimisation', 'Formule'],
        keywords: ['bfr', 'besoin fonds roulement', 'trésorerie', 'stocks', 'fournisseurs', 'pcg'],
        image: '/images/bfr.png'
    },
    {
        slug: 'marge-nette-vs-brute',
        title: 'Marge nette vs marge brute : différences et calculs',
        description: 'Comprenez la différence entre marge brute et marge nette avec formules et benchmarks sectoriels',
        displayDate: '10 décembre 2025',
        publishedAt: '2025-11-28',
        readTime: '7 min',
        category: 'Rentabilité',
        tags: ['Marges', 'Rentabilité', 'Calcul', 'Benchmark'],
        keywords: ['marge nette', 'marge brute', 'rentabilité', 'profitabilité', 'ebitda'],
        image: '/images/marge.png'
    },
    {
        slug: 'cash-flow-previsionnel-pme',
        title: 'Cash flow prévisionnel : méthode pratique pour PME',
        description: 'Guide complet pour construire un cash flow prévisionnel fiable et anticiper vos besoins de trésorerie',
        displayDate: '5 décembre 2025',
        publishedAt: '2025-11-28',
        readTime: '9 min',
        category: 'Trésorerie',
        tags: ['Cash Flow', 'Prévisionnel', 'PME', 'Méthode'],
        keywords: ['cash flow', 'prévisionnel', 'trésorerie', 'budget', 'pme'],
        image: '/images/cash-flow-prev.png'
    },
    {
        slug: 'top-7-kpis-startups-saas',
        title: 'Top 7 KPIs financiers pour startups SaaS',
        description: 'Les indicateurs essentiels pour piloter une startup SaaS : MRR, Churn, CAC, LTV et plus',
        displayDate: '2 décembre 2025',
        publishedAt: '2025-11-28',
        readTime: '8 min',
        category: 'SaaS',
        tags: ['SaaS', 'MRR', 'Churn', 'CAC', 'LTV'],
        keywords: ['kpi saas', 'mrr', 'arr', 'churn', 'cac', 'ltv', 'startup'],
        image: '/images/7kpisfiSaaS.png'
    },
    {
        slug: 'creances-clients-reduire-impayes',
        title: 'Créances clients : comment réduire les impayés',
        description: 'Stratégies concrètes pour améliorer le recouvrement et diminuer les retards de paiement',
        displayDate: '25 novembre 2025',
        publishedAt: '2025-11-28',
        readTime: '7 min',
        category: 'Recouvrement',
        tags: ['Créances', 'Impayés', 'Recouvrement', 'DSO'],
        keywords: ['créances', 'impayés', 'recouvrement', 'relance', 'facture', 'dso'],
        image: '/images/impayés.png'
    },
    {
        slug: 'tresorerie-pme-5-erreurs-eviter',
        title: 'Trésorerie PME : 5 erreurs à éviter',
        description: 'Les erreurs fréquentes qui mettent en péril la trésorerie des PME et comment les éviter',
        displayDate: '18 novembre 2025',
        publishedAt: '2025-11-28',
        readTime: '6 min',
        category: 'Trésorerie',
        tags: ['Trésorerie', 'PME', 'Erreurs', 'Conseils'],
        keywords: ['trésorerie', 'pme', 'erreurs', 'cash', 'gestion financière'],
        image: '/images/5-erreurs.png'
    },
    {
        slug: 'ratio-liquidite-interpretation',
        title: 'Ratio de liquidité PME : 3 formules et seuils',
        description:
            'Current, quick et cash ratio : calculez vos seuils, comparez à votre secteur et voyez si vous pouvez payer vos dettes court terme. Formules incluses.',
        displayDate: '12 novembre 2025',
        publishedAt: '2025-11-28',
        readTime: '8 min',
        category: 'Analyse',
        tags: ['Ratios', 'Liquidité', 'Analyse', 'Santé financière'],
        keywords: ['ratio liquidité', 'current ratio', 'quick ratio', 'solvabilité', 'analyse financière'],
        image: '/images/ratio-liquidité.png'
    },
    {
        slug: 'budget-previsionnel-dashboard-ia',
        title: 'Budget prévisionnel : template Excel vs dashboard IA',
        description: 'Comparaison des méthodes pour construire et suivre votre budget prévisionnel efficacement',
        displayDate: '5 novembre 2025',
        publishedAt: '2025-11-28',
        readTime: '7 min',
        category: 'Outils',
        tags: ['Budget', 'IA', 'Excel', 'Dashboard'],
        keywords: ['budget', 'prévisionnel', 'excel', 'ia', 'automatisation', 'dashboard'],
        image: '/images/moi-bureau.png'
    },
    {
        slug: 'reduire-dso-50-pourcent-90-jours',
        title: 'Réduire son DSO de 50% en 90 jours : Guide Pratique',
        description: 'Méthode éprouvée pour améliorer votre DSO et libérer jusqu\'à 200k€ de trésorerie. 10 actions concrètes + cas client.',
        displayDate: '28 janvier 2026',
        publishedAt: '2026-01-28',
        readTime: '12 min',
        category: 'Trésorerie',
        tags: ['DSO', 'Réduire DSO', 'Trésorerie', 'Recouvrement', 'PME'],
        keywords: ['réduire dso', 'dso 2026', 'trésorerie pme', 'délai paiement', 'cash management'],
        featured: true,
        image: '/images/bureau-nuit.png'
    },
    {
        slug: 'bfr-negatif-bon-ou-mauvais',
        title: 'BFR Négatif : Bon ou Mauvais pour Votre Entreprise ?',
        description: 'Un BFR négatif est-il signe de bonne santé ou de danger ? Exemples par secteur : grande distribution, SaaS, e-commerce.',
        displayDate: '28 janvier 2026',
        publishedAt: '2026-01-28',
        readTime: '10 min',
        category: 'Trésorerie',
        tags: ['BFR', 'BFR Négatif', 'Trésorerie', 'Analyse'],
        keywords: ['bfr négatif', 'besoin fonds roulement', 'cash flow', 'saas', 'grande distribution'],
        image: '/images/bfr.png'
    },
    {
        slug: 'dso-vs-dpo-optimiser-tresorerie',
        title: 'DSO vs DPO : Optimiser l\'Équilibre Clients-Fournisseurs',
        description: 'Comprendre la différence DSO/DPO et optimiser votre Cash Conversion Cycle pour libérer de la trésorerie.',
        displayDate: '28 janvier 2026',
        publishedAt: '2026-01-28',
        readTime: '9 min',
        category: 'Trésorerie',
        tags: ['DSO', 'DPO', 'Cash Conversion Cycle', 'Trésorerie'],
        keywords: ['dso', 'dpo', 'cash conversion cycle', 'trésorerie', 'fournisseurs clients'],
        image: '/images/vue-NY.png'
    },
    {
        slug: 'daf-externalise-pme-prix-2026',
        title: 'DAF Externalisé PME : Prix, Tarifs et ROI en 2026',
        description: 'Combien coûte un DAF externalisé pour une PME ? Grille tarifaire 2026, comparaison DAF temps plein vs externalisé, et calcul du ROI réel.',
        displayDate: '6 février 2026',
        publishedAt: '2026-02-06',
        readTime: '15 min',
        category: 'Gestion',
        tags: ['DAF Externalisé', 'Prix', 'Tarifs', 'ROI', 'PME', 'CFO'],
        keywords: ['daf externalisé prix', 'tarif daf externalisé', 'coût daf pme', 'fractional cfo prix', 'roi daf'],
        featured: true,
        image: '/images/bureau.png'
    },
    {
        slug: 'probleme-tresorerie-pme-10-signes',
        title: 'Problème de Trésorerie PME : 10 Signes d\'Alerte (et Solutions)',
        description: 'Comment détecter un problème de trésorerie avant qu\'il ne soit trop tard ? 10 signaux d\'alerte + plan d\'action en 30 jours.',
        displayDate: '6 février 2026',
        publishedAt: '2026-02-06',
        readTime: '12 min',
        category: 'Trésorerie',
        tags: ['Problème Trésorerie', 'PME', 'Alerte', 'Cash', 'Solutions'],
        keywords: ['problème trésorerie pme', 'difficulté trésorerie', 'alerte trésorerie', 'manque cash', 'solutions trésorerie'],
        featured: true,
        image: '/images/bureau-nuit.png'
    },
    {
        slug: 'calculer-bfr-excel-template-2026',
        title: 'Calculer son BFR avec Excel : Template Gratuit 2026',
        description: 'Tutoriel complet pour calculer et analyser votre BFR dans Excel. Template gratuit + formules automatiques + exemples par secteur.',
        displayDate: '6 février 2026',
        publishedAt: '2026-02-06',
        readTime: '10 min',
        category: 'Trésorerie',
        tags: ['BFR', 'Excel', 'Template', 'Calcul', 'Formules'],
        keywords: ['calculer bfr excel', 'template bfr gratuit', 'formule bfr excel', 'bfr tutorial', 'besoin fonds roulement excel'],
        image: '/images/bfr.png'
    },
    {
        slug: 'pilotage-tresorerie-90-jours-methode',
        title: 'Pilotage Trésorerie 90 Jours : Méthode Complète PME',
        description: 'Comment piloter sa trésorerie sur 90 jours ? Méthode éprouvée avec prévisionnel, suivi hebdomadaire et alertes automatiques.',
        displayDate: '6 février 2026',
        publishedAt: '2026-02-06',
        readTime: '14 min',
        category: 'Trésorerie',
        tags: ['Pilotage Trésorerie', '90 Jours', 'Prévisionnel', 'Méthode', 'PME'],
        keywords: ['pilotage trésorerie', 'prévisionnel 90 jours', 'gestion trésorerie pme', 'suivi trésorerie', 'cash management'],
        image: '/images/cash-flow-prev.png'
    },
    {
        slug: 'fractional-cfo-france-guide-2026',
        title: 'Fractional CFO France : Guide Complet 2026',
        description: 'Qu\'est-ce qu\'un Fractional CFO ? Différences avec DAF externalisé, cas d\'usage, tarifs et comment choisir le bon profil pour votre PME.',
        displayDate: '6 février 2026',
        publishedAt: '2026-02-06',
        readTime: '13 min',
        category: 'Gestion',
        tags: ['Fractional CFO', 'CFO', 'DAF', 'France', 'Guide'],
        keywords: ['fractional cfo france', 'cfo temps partiel', 'daf externalisé', 'part-time cfo', 'cfo pme'],
        image: '/images/moi-bureau.png'
    }
]
